version: '1.2'

services:
  kl_crawl:
    container_name: kl_crawl
    build: .
    image: kl_crawl:latest
    volumes:
      - data:/usr/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - wd_url=http://192.168.0.2:4444/wd/hub

volumes:
  data:
    external: true